---
title: "National Usage of Complementary Health Approaches in Children with Developmental Disabilities"
author: "Michael Ching, MD, MPH, Hawaii Permanente Medical Group, michael.s.ching@kp.org"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: word_document
---

# Background
Complementary health approaches (CHA) include vitamins, minerals, supplements, mind-body interventions, and manipulation/body based methods. Children with developmental disabilities have been reported to use these interventions frequently although there is substantial variability in estimates of usage (28-95%). Prior work has been limited by selection bias and sample size. This study estimates the frequency of CHA in a nationally representative sample.

# Methods
Data were from the 2012 National Health Interview Survey. This survey contained a child complementary and alternative medicine supplement administered to parents and caregivers. I used survey weights to obtain national population estimates of the frequency of CHA in children with autism spectrum disorder (ASD), intellectual disability (ID), and other developmental disabilities (DD). I used survey weighted chi-square testing and logistic regression to determine whether children with these diagnoses differed from those without in their usage of CHA and to estimate odds ratios. 

# Results
The sample consisted of 13,275 children, of whom 156 (1.2%) had ASD, 137 (1.0%) had ID, and 592 (4.7%) had DD. Vitamin, mineral, and herbal and dietary supplements were often used, with 65% of children with ASD, ID, or DD using multivitamins, 13% using minerals, and 14% using herbs and other non-vitamin supplments. The prevalence of any CHA use other than vitamins and minerals in children with disabilities was 12.3% compared to 7.2% of children without ASD, ID, or DD. The odds of CHA use (other than vitamins and minerals) was higher in children with ASD (odds ratio = 2.1, 95% confidence interval 1.1-4.0) and children with DD (OR = 1.9, 95% CI 1.4-2.6) compared to children without these conditions. The odds of CHA use in children with ID did not differ significantly from children without ID.

# Conclusion
Children with ASD and other developmental disabilities use complementary health approaches roughly twice as often as children without these conditions.